version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/Nebus
    environment:
      - DATABASE_URL=sqlite:///./test.db  # Убедитесь, что ваш проект использует эту переменную
    
    # Specify the .env file path
    env_file:
      - ./.env